apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ce8i3g57j-python 
  janus-idp.io/tekton: ce8i3g57j-python
  backstage.io/kubernetes-id: ce8i3g57j-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ce8i3g57j-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml