apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ce8i3g57j-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ce8i3g57j-python 
  name: ce8i3g57j-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ce8i3g57j-python 
